"""listings table updated

Revision ID: ecd9e7088e99
Revises: d9591b2bff69
Create Date: 2020-12-23 12:45:14.677217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd9e7088e99'
down_revision = 'd9591b2bff69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('building_sqft', sa.Integer(), nullable=True))
    op.add_column('listing', sa.Column('description', sa.String(length=140), nullable=True))
    op.add_column('listing', sa.Column('has_pool', sa.Boolean(), nullable=True))
    op.add_column('listing', sa.Column('lot_sqft', sa.Integer(), nullable=True))
    op.add_column('listing', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('listing', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_listing_address'), 'listing', ['address'], unique=True)
    op.create_index(op.f('ix_listing_building_sqft'), 'listing', ['building_sqft'], unique=False)
    op.create_index(op.f('ix_listing_lot_sqft'), 'listing', ['lot_sqft'], unique=False)
    op.create_index(op.f('ix_listing_price'), 'listing', ['price'], unique=False)
    op.create_index(op.f('ix_listing_year'), 'listing', ['year'], unique=False)
    op.create_index(op.f('ix_listing_zipcode'), 'listing', ['zipcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_zipcode'), table_name='listing')
    op.drop_index(op.f('ix_listing_year'), table_name='listing')
    op.drop_index(op.f('ix_listing_price'), table_name='listing')
    op.drop_index(op.f('ix_listing_lot_sqft'), table_name='listing')
    op.drop_index(op.f('ix_listing_building_sqft'), table_name='listing')
    op.drop_index(op.f('ix_listing_address'), table_name='listing')
    op.drop_column('listing', 'zipcode')
    op.drop_column('listing', 'year')
    op.drop_column('listing', 'lot_sqft')
    op.drop_column('listing', 'has_pool')
    op.drop_column('listing', 'description')
    op.drop_column('listing', 'building_sqft')
    # ### end Alembic commands ###
